---
title: "Female_Athlete"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(gganimate)
```

```{r}
sidata_201015 <- read_csv("Female_Athlete_Data/sicover_update.csv")
write_rds(sidata_201015, "Female_Athlete/sidata_201015.rds")

view(sidata_201015)

sidata_201015 <- sidata_201015 %>%
  clean_names()

glimpse(sidata_201015)
view(sidata_201015)

```

```{r}

p <- ggplot(sidata_201015, aes(x = year, y = frequency, fill = on_cover)) +
      geom_col() +
  scale_fill_manual(values = c("darkcyan", "coral", "azure4", "darkolivegreen",
                               "chocolate", "darkseagreen"), 
                    guide_legend(title="Who is on the cover?")) +
  labs(title = "Comparison of Who is on Sports Illustrated Covers 
      throughout the Decade",
       x = "Year", 
       y = "Number of Covers") +
  theme_minimal() +
  scale_x_continuous(breaks = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020), labels = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020))

p

```

